//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PuzzleInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PuzzleInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PuzzleInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PuzzleInput"",
    ""maps"": [
        {
            ""name"": ""PuzzleBlock"",
            ""id"": ""cf439c4a-4a62-4fb8-91fe-e8984dc92487"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8a003f9-a495-490f-af3a-21549e6a9873"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4478f6d9-a380-46ef-903b-6632b02b7fac"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PuzzleBlock
        m_PuzzleBlock = asset.FindActionMap("PuzzleBlock", throwIfNotFound: true);
        m_PuzzleBlock_Touch = m_PuzzleBlock.FindAction("Touch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PuzzleBlock
    private readonly InputActionMap m_PuzzleBlock;
    private List<IPuzzleBlockActions> m_PuzzleBlockActionsCallbackInterfaces = new List<IPuzzleBlockActions>();
    private readonly InputAction m_PuzzleBlock_Touch;
    public struct PuzzleBlockActions
    {
        private @PuzzleInput m_Wrapper;
        public PuzzleBlockActions(@PuzzleInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_PuzzleBlock_Touch;
        public InputActionMap Get() { return m_Wrapper.m_PuzzleBlock; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PuzzleBlockActions set) { return set.Get(); }
        public void AddCallbacks(IPuzzleBlockActions instance)
        {
            if (instance == null || m_Wrapper.m_PuzzleBlockActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PuzzleBlockActionsCallbackInterfaces.Add(instance);
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
        }

        private void UnregisterCallbacks(IPuzzleBlockActions instance)
        {
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
        }

        public void RemoveCallbacks(IPuzzleBlockActions instance)
        {
            if (m_Wrapper.m_PuzzleBlockActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPuzzleBlockActions instance)
        {
            foreach (var item in m_Wrapper.m_PuzzleBlockActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PuzzleBlockActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PuzzleBlockActions @PuzzleBlock => new PuzzleBlockActions(this);
    public interface IPuzzleBlockActions
    {
        void OnTouch(InputAction.CallbackContext context);
    }
}
